// GENERADO por scripts/generate-paises.mjs — no editar a mano.
// Fuente: libphonenumber-js/min (países y ladas) + Intl.DisplayNames('es') de
// Node (nombres). 245 países; México primero, el resto en orden
// alfabético. Sin bandera emoji a propósito (CLAUDE.md §3, bloque del teléfono).

import type { CountryCode } from 'libphonenumber-js/min';

export type Pais = { iso: CountryCode; nombre: string; lada: string };

export const PAISES: readonly Pais[] = [
  { iso: 'MX', nombre: "México", lada: '+52' },
  { iso: 'AF', nombre: "Afganistán", lada: '+93' },
  { iso: 'AL', nombre: "Albania", lada: '+355' },
  { iso: 'DE', nombre: "Alemania", lada: '+49' },
  { iso: 'AD', nombre: "Andorra", lada: '+376' },
  { iso: 'AO', nombre: "Angola", lada: '+244' },
  { iso: 'AI', nombre: "Anguila", lada: '+1' },
  { iso: 'AG', nombre: "Antigua y Barbuda", lada: '+1' },
  { iso: 'SA', nombre: "Arabia Saudí", lada: '+966' },
  { iso: 'DZ', nombre: "Argelia", lada: '+213' },
  { iso: 'AR', nombre: "Argentina", lada: '+54' },
  { iso: 'AM', nombre: "Armenia", lada: '+374' },
  { iso: 'AW', nombre: "Aruba", lada: '+297' },
  { iso: 'AU', nombre: "Australia", lada: '+61' },
  { iso: 'AT', nombre: "Austria", lada: '+43' },
  { iso: 'AZ', nombre: "Azerbaiyán", lada: '+994' },
  { iso: 'BS', nombre: "Bahamas", lada: '+1' },
  { iso: 'BD', nombre: "Bangladés", lada: '+880' },
  { iso: 'BB', nombre: "Barbados", lada: '+1' },
  { iso: 'BH', nombre: "Baréin", lada: '+973' },
  { iso: 'BE', nombre: "Bélgica", lada: '+32' },
  { iso: 'BZ', nombre: "Belice", lada: '+501' },
  { iso: 'BJ', nombre: "Benín", lada: '+229' },
  { iso: 'BM', nombre: "Bermudas", lada: '+1' },
  { iso: 'BY', nombre: "Bielorrusia", lada: '+375' },
  { iso: 'BO', nombre: "Bolivia", lada: '+591' },
  { iso: 'BA', nombre: "Bosnia y Herzegovina", lada: '+387' },
  { iso: 'BW', nombre: "Botsuana", lada: '+267' },
  { iso: 'BR', nombre: "Brasil", lada: '+55' },
  { iso: 'BN', nombre: "Brunéi", lada: '+673' },
  { iso: 'BG', nombre: "Bulgaria", lada: '+359' },
  { iso: 'BF', nombre: "Burkina Faso", lada: '+226' },
  { iso: 'BI', nombre: "Burundi", lada: '+257' },
  { iso: 'BT', nombre: "Bután", lada: '+975' },
  { iso: 'CV', nombre: "Cabo Verde", lada: '+238' },
  { iso: 'KH', nombre: "Camboya", lada: '+855' },
  { iso: 'CM', nombre: "Camerún", lada: '+237' },
  { iso: 'CA', nombre: "Canadá", lada: '+1' },
  { iso: 'BQ', nombre: "Caribe neerlandés", lada: '+599' },
  { iso: 'QA', nombre: "Catar", lada: '+974' },
  { iso: 'TD', nombre: "Chad", lada: '+235' },
  { iso: 'CZ', nombre: "Chequia", lada: '+420' },
  { iso: 'CL', nombre: "Chile", lada: '+56' },
  { iso: 'CN', nombre: "China", lada: '+86' },
  { iso: 'CY', nombre: "Chipre", lada: '+357' },
  { iso: 'VA', nombre: "Ciudad del Vaticano", lada: '+39' },
  { iso: 'CO', nombre: "Colombia", lada: '+57' },
  { iso: 'KM', nombre: "Comoras", lada: '+269' },
  { iso: 'CG', nombre: "Congo", lada: '+242' },
  { iso: 'KP', nombre: "Corea del Norte", lada: '+850' },
  { iso: 'KR', nombre: "Corea del Sur", lada: '+82' },
  { iso: 'CR', nombre: "Costa Rica", lada: '+506' },
  { iso: 'CI', nombre: "Côte d’Ivoire", lada: '+225' },
  { iso: 'HR', nombre: "Croacia", lada: '+385' },
  { iso: 'CU', nombre: "Cuba", lada: '+53' },
  { iso: 'CW', nombre: "Curazao", lada: '+599' },
  { iso: 'DK', nombre: "Dinamarca", lada: '+45' },
  { iso: 'DM', nombre: "Dominica", lada: '+1' },
  { iso: 'EC', nombre: "Ecuador", lada: '+593' },
  { iso: 'EG', nombre: "Egipto", lada: '+20' },
  { iso: 'SV', nombre: "El Salvador", lada: '+503' },
  { iso: 'AE', nombre: "Emiratos Árabes Unidos", lada: '+971' },
  { iso: 'ER', nombre: "Eritrea", lada: '+291' },
  { iso: 'SK', nombre: "Eslovaquia", lada: '+421' },
  { iso: 'SI', nombre: "Eslovenia", lada: '+386' },
  { iso: 'ES', nombre: "España", lada: '+34' },
  { iso: 'US', nombre: "Estados Unidos", lada: '+1' },
  { iso: 'EE', nombre: "Estonia", lada: '+372' },
  { iso: 'SZ', nombre: "Esuatini", lada: '+268' },
  { iso: 'ET', nombre: "Etiopía", lada: '+251' },
  { iso: 'PH', nombre: "Filipinas", lada: '+63' },
  { iso: 'FI', nombre: "Finlandia", lada: '+358' },
  { iso: 'FJ', nombre: "Fiyi", lada: '+679' },
  { iso: 'FR', nombre: "Francia", lada: '+33' },
  { iso: 'GA', nombre: "Gabón", lada: '+241' },
  { iso: 'GM', nombre: "Gambia", lada: '+220' },
  { iso: 'GE', nombre: "Georgia", lada: '+995' },
  { iso: 'GH', nombre: "Ghana", lada: '+233' },
  { iso: 'GI', nombre: "Gibraltar", lada: '+350' },
  { iso: 'GD', nombre: "Granada", lada: '+1' },
  { iso: 'GR', nombre: "Grecia", lada: '+30' },
  { iso: 'GL', nombre: "Groenlandia", lada: '+299' },
  { iso: 'GP', nombre: "Guadalupe", lada: '+590' },
  { iso: 'GU', nombre: "Guam", lada: '+1' },
  { iso: 'GT', nombre: "Guatemala", lada: '+502' },
  { iso: 'GF', nombre: "Guayana Francesa", lada: '+594' },
  { iso: 'GG', nombre: "Guernesey", lada: '+44' },
  { iso: 'GN', nombre: "Guinea", lada: '+224' },
  { iso: 'GQ', nombre: "Guinea Ecuatorial", lada: '+240' },
  { iso: 'GW', nombre: "Guinea-Bisáu", lada: '+245' },
  { iso: 'GY', nombre: "Guyana", lada: '+592' },
  { iso: 'HT', nombre: "Haití", lada: '+509' },
  { iso: 'HN', nombre: "Honduras", lada: '+504' },
  { iso: 'HU', nombre: "Hungría", lada: '+36' },
  { iso: 'IN', nombre: "India", lada: '+91' },
  { iso: 'ID', nombre: "Indonesia", lada: '+62' },
  { iso: 'IQ', nombre: "Irak", lada: '+964' },
  { iso: 'IR', nombre: "Irán", lada: '+98' },
  { iso: 'IE', nombre: "Irlanda", lada: '+353' },
  { iso: 'AC', nombre: "Isla de la Ascensión", lada: '+247' },
  { iso: 'IM', nombre: "Isla de Man", lada: '+44' },
  { iso: 'CX', nombre: "Isla de Navidad", lada: '+61' },
  { iso: 'NF', nombre: "Isla Norfolk", lada: '+672' },
  { iso: 'IS', nombre: "Islandia", lada: '+354' },
  { iso: 'AX', nombre: "Islas Aland", lada: '+358' },
  { iso: 'KY', nombre: "Islas Caimán", lada: '+1' },
  { iso: 'CC', nombre: "Islas Cocos", lada: '+61' },
  { iso: 'CK', nombre: "Islas Cook", lada: '+682' },
  { iso: 'FO', nombre: "Islas Feroe", lada: '+298' },
  { iso: 'FK', nombre: "Islas Malvinas", lada: '+500' },
  { iso: 'MP', nombre: "Islas Marianas del Norte", lada: '+1' },
  { iso: 'MH', nombre: "Islas Marshall", lada: '+692' },
  { iso: 'SB', nombre: "Islas Salomón", lada: '+677' },
  { iso: 'TC', nombre: "Islas Turcas y Caicos", lada: '+1' },
  { iso: 'VG', nombre: "Islas Vírgenes Británicas", lada: '+1' },
  { iso: 'VI', nombre: "Islas Vírgenes de EE. UU.", lada: '+1' },
  { iso: 'IL', nombre: "Israel", lada: '+972' },
  { iso: 'IT', nombre: "Italia", lada: '+39' },
  { iso: 'JM', nombre: "Jamaica", lada: '+1' },
  { iso: 'JP', nombre: "Japón", lada: '+81' },
  { iso: 'JE', nombre: "Jersey", lada: '+44' },
  { iso: 'JO', nombre: "Jordania", lada: '+962' },
  { iso: 'KZ', nombre: "Kazajistán", lada: '+7' },
  { iso: 'KE', nombre: "Kenia", lada: '+254' },
  { iso: 'KG', nombre: "Kirguistán", lada: '+996' },
  { iso: 'KI', nombre: "Kiribati", lada: '+686' },
  { iso: 'XK', nombre: "Kosovo", lada: '+383' },
  { iso: 'KW', nombre: "Kuwait", lada: '+965' },
  { iso: 'LA', nombre: "Laos", lada: '+856' },
  { iso: 'LS', nombre: "Lesoto", lada: '+266' },
  { iso: 'LV', nombre: "Letonia", lada: '+371' },
  { iso: 'LB', nombre: "Líbano", lada: '+961' },
  { iso: 'LR', nombre: "Liberia", lada: '+231' },
  { iso: 'LY', nombre: "Libia", lada: '+218' },
  { iso: 'LI', nombre: "Liechtenstein", lada: '+423' },
  { iso: 'LT', nombre: "Lituania", lada: '+370' },
  { iso: 'LU', nombre: "Luxemburgo", lada: '+352' },
  { iso: 'MK', nombre: "Macedonia del Norte", lada: '+389' },
  { iso: 'MG', nombre: "Madagascar", lada: '+261' },
  { iso: 'MY', nombre: "Malasia", lada: '+60' },
  { iso: 'MW', nombre: "Malaui", lada: '+265' },
  { iso: 'MV', nombre: "Maldivas", lada: '+960' },
  { iso: 'ML', nombre: "Mali", lada: '+223' },
  { iso: 'MT', nombre: "Malta", lada: '+356' },
  { iso: 'MA', nombre: "Marruecos", lada: '+212' },
  { iso: 'MQ', nombre: "Martinica", lada: '+596' },
  { iso: 'MU', nombre: "Mauricio", lada: '+230' },
  { iso: 'MR', nombre: "Mauritania", lada: '+222' },
  { iso: 'YT', nombre: "Mayotte", lada: '+262' },
  { iso: 'FM', nombre: "Micronesia", lada: '+691' },
  { iso: 'MD', nombre: "Moldavia", lada: '+373' },
  { iso: 'MC', nombre: "Mónaco", lada: '+377' },
  { iso: 'MN', nombre: "Mongolia", lada: '+976' },
  { iso: 'ME', nombre: "Montenegro", lada: '+382' },
  { iso: 'MS', nombre: "Montserrat", lada: '+1' },
  { iso: 'MZ', nombre: "Mozambique", lada: '+258' },
  { iso: 'MM', nombre: "Myanmar (Birmania)", lada: '+95' },
  { iso: 'NA', nombre: "Namibia", lada: '+264' },
  { iso: 'NR', nombre: "Nauru", lada: '+674' },
  { iso: 'NP', nombre: "Nepal", lada: '+977' },
  { iso: 'NI', nombre: "Nicaragua", lada: '+505' },
  { iso: 'NE', nombre: "Níger", lada: '+227' },
  { iso: 'NG', nombre: "Nigeria", lada: '+234' },
  { iso: 'NU', nombre: "Niue", lada: '+683' },
  { iso: 'NO', nombre: "Noruega", lada: '+47' },
  { iso: 'NC', nombre: "Nueva Caledonia", lada: '+687' },
  { iso: 'NZ', nombre: "Nueva Zelanda", lada: '+64' },
  { iso: 'OM', nombre: "Omán", lada: '+968' },
  { iso: 'NL', nombre: "Países Bajos", lada: '+31' },
  { iso: 'PK', nombre: "Pakistán", lada: '+92' },
  { iso: 'PW', nombre: "Palaos", lada: '+680' },
  { iso: 'PA', nombre: "Panamá", lada: '+507' },
  { iso: 'PG', nombre: "Papúa Nueva Guinea", lada: '+675' },
  { iso: 'PY', nombre: "Paraguay", lada: '+595' },
  { iso: 'PE', nombre: "Perú", lada: '+51' },
  { iso: 'PF', nombre: "Polinesia Francesa", lada: '+689' },
  { iso: 'PL', nombre: "Polonia", lada: '+48' },
  { iso: 'PT', nombre: "Portugal", lada: '+351' },
  { iso: 'PR', nombre: "Puerto Rico", lada: '+1' },
  { iso: 'HK', nombre: "RAE de Hong Kong (China)", lada: '+852' },
  { iso: 'MO', nombre: "RAE de Macao (China)", lada: '+853' },
  { iso: 'GB', nombre: "Reino Unido", lada: '+44' },
  { iso: 'CF', nombre: "República Centroafricana", lada: '+236' },
  { iso: 'CD', nombre: "República Democrática del Congo", lada: '+243' },
  { iso: 'DO', nombre: "República Dominicana", lada: '+1' },
  { iso: 'RE', nombre: "Reunión", lada: '+262' },
  { iso: 'RW', nombre: "Ruanda", lada: '+250' },
  { iso: 'RO', nombre: "Rumanía", lada: '+40' },
  { iso: 'RU', nombre: "Rusia", lada: '+7' },
  { iso: 'EH', nombre: "Sáhara Occidental", lada: '+212' },
  { iso: 'WS', nombre: "Samoa", lada: '+685' },
  { iso: 'AS', nombre: "Samoa Americana", lada: '+1' },
  { iso: 'BL', nombre: "San Bartolomé", lada: '+590' },
  { iso: 'KN', nombre: "San Cristóbal y Nieves", lada: '+1' },
  { iso: 'SM', nombre: "San Marino", lada: '+378' },
  { iso: 'MF', nombre: "San Martín", lada: '+590' },
  { iso: 'PM', nombre: "San Pedro y Miquelón", lada: '+508' },
  { iso: 'VC', nombre: "San Vicente y las Granadinas", lada: '+1' },
  { iso: 'SH', nombre: "Santa Elena", lada: '+290' },
  { iso: 'LC', nombre: "Santa Lucía", lada: '+1' },
  { iso: 'ST', nombre: "Santo Tomé y Príncipe", lada: '+239' },
  { iso: 'SN', nombre: "Senegal", lada: '+221' },
  { iso: 'RS', nombre: "Serbia", lada: '+381' },
  { iso: 'SC', nombre: "Seychelles", lada: '+248' },
  { iso: 'SL', nombre: "Sierra Leona", lada: '+232' },
  { iso: 'SG', nombre: "Singapur", lada: '+65' },
  { iso: 'SX', nombre: "Sint Maarten", lada: '+1' },
  { iso: 'SY', nombre: "Siria", lada: '+963' },
  { iso: 'SO', nombre: "Somalia", lada: '+252' },
  { iso: 'LK', nombre: "Sri Lanka", lada: '+94' },
  { iso: 'ZA', nombre: "Sudáfrica", lada: '+27' },
  { iso: 'SD', nombre: "Sudán", lada: '+249' },
  { iso: 'SS', nombre: "Sudán del Sur", lada: '+211' },
  { iso: 'SE', nombre: "Suecia", lada: '+46' },
  { iso: 'CH', nombre: "Suiza", lada: '+41' },
  { iso: 'SR', nombre: "Surinam", lada: '+597' },
  { iso: 'SJ', nombre: "Svalbard y Jan Mayen", lada: '+47' },
  { iso: 'TH', nombre: "Tailandia", lada: '+66' },
  { iso: 'TW', nombre: "Taiwán", lada: '+886' },
  { iso: 'TZ', nombre: "Tanzania", lada: '+255' },
  { iso: 'TJ', nombre: "Tayikistán", lada: '+992' },
  { iso: 'IO', nombre: "Territorio Británico del Océano Índico", lada: '+246' },
  { iso: 'PS', nombre: "Territorios Palestinos", lada: '+970' },
  { iso: 'TL', nombre: "Timor-Leste", lada: '+670' },
  { iso: 'TG', nombre: "Togo", lada: '+228' },
  { iso: 'TK', nombre: "Tokelau", lada: '+690' },
  { iso: 'TO', nombre: "Tonga", lada: '+676' },
  { iso: 'TT', nombre: "Trinidad y Tobago", lada: '+1' },
  { iso: 'TA', nombre: "Tristán de Acuña", lada: '+290' },
  { iso: 'TN', nombre: "Túnez", lada: '+216' },
  { iso: 'TM', nombre: "Turkmenistán", lada: '+993' },
  { iso: 'TR', nombre: "Turquía", lada: '+90' },
  { iso: 'TV', nombre: "Tuvalu", lada: '+688' },
  { iso: 'UA', nombre: "Ucrania", lada: '+380' },
  { iso: 'UG', nombre: "Uganda", lada: '+256' },
  { iso: 'UY', nombre: "Uruguay", lada: '+598' },
  { iso: 'UZ', nombre: "Uzbekistán", lada: '+998' },
  { iso: 'VU', nombre: "Vanuatu", lada: '+678' },
  { iso: 'VE', nombre: "Venezuela", lada: '+58' },
  { iso: 'VN', nombre: "Vietnam", lada: '+84' },
  { iso: 'WF', nombre: "Wallis y Futuna", lada: '+681' },
  { iso: 'YE', nombre: "Yemen", lada: '+967' },
  { iso: 'DJ', nombre: "Yibuti", lada: '+253' },
  { iso: 'ZM', nombre: "Zambia", lada: '+260' },
  { iso: 'ZW', nombre: "Zimbabue", lada: '+263' },
];

/**
 * El país de un ISO, o México (el primero) si no está en la lista. El ISO sale
 * de `separarE164()`/`paisDePegado()` (`src/lib/validacion-perfil.ts`), que
 * usan la MISMA metadata, así que el fallback solo cubre una lista vieja.
 */
export function paisPorIso(iso: string): Pais {
  return PAISES.find((p) => p.iso === iso) ?? PAISES[0];
}
